version: "2.2"

volumes:
  wp:
    driver: local
    driver_opts:
      o: 'bind'
      type: 'none'
      device: "/home/rhilda/data/wp"
  db:
    driver: local
    driver_opts:
      o: 'bind'
      type: 'none'
      device: "/home/rhilda/data/db"
networks:
  net:

services:
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    volumes:
      - db:/var/lib/mysql/
    environment:
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_HOST=${ACCESS_HOST}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PORT=${MARIADB_PORT}
    restart: always
    networks:
      - net
  wordpress:
    build: ./requirements/wordpress_php/
    container_name: wordpress
    depends_on:
      - mariadb
    restart: always
    volumes:
      - wp:/var/www/wordpress
    environment:
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PORT=${MARIADB_PORT}
      - WP_SITE=${WP_SITE}
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN=${WP_ADMIN}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_EMAIL=${WP_EMAIL}
      - WP_USER=${WP_USER}
      - WP_USER_PASSWORD=${WP_USER_PASSWORD}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
    networks:
      - net
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    volumes:
      - wp:/var/www/wordpress
    ports:
      - 443:443
    depends_on:
      - wordpress
    networks:
      - net
    restart: always